### ISSUE TITLE
Build on Mac OS with Java 8 fails in assembly

### ISSUE THREAD

**Issue by sasconsul** [headwirecom/aemdc#12]
I just downloaded and tried to build aemdc on my Mac OS machine with Java 8.  Maven reports:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (resource-zips) on project aemdc: Execution resource-zips of goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single failed: group id '334330370' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit -> [Help 1]
```

The problem is that some users get very large group id's.  The solution is to use posix mode as noted in  [maven-assembly-plugin doc](https://maven.apache.org/plugins/maven-assembly-plugin/faq.html#tarFileModes)

[bld_log.txt](https://github.com/headwirecom/aemdc/files/1082957/bld_log.txt)

**Comment by mtstv** [comment]
Fixed and merged
#13
