### ISSUE TITLE
If the App is started from another place that the aemdc-config file the AEMDC does not work

### ISSUE THREAD

**Issue by schaefa** [headwirecom/aemdc#4]
File operations are all relative to the startup directory of AEMDC. For IntelliJ this is not going to work.

I added this to the Config:

  private static File projectRoot = new File(".");

  public static String getProjectRootPath() {
    return projectRoot.getPath();
  }

To make config work relative to my project but creating components does not work as for example CopyDIrCommand does copy it to the startup folder of IntelliJ. All file operation have to be made relative to a given project root.

Tomorrow I will clean up my changes, create a branch and commit.

**Comment by schaefa** [comment]
Latest changes from Ruben seems to do the trick.

**Comment by mtstv** [comment]
Could you confirm please whether it has been fixed by you with the last "pull request"?

**Comment by schaefa** [comment]
Yes, that is fixed.
