### ISSUE TITLE
Console and System Out / Err Redirection causes issues in IntelliJ

### ISSUE THREAD

**Issue by schaefa** [headwirecom/aemdc#6]
There are two different issues with the System Out / Err redirection when using AEMDC inside IntelliJ:

1) In IntelliJ there are dependencies that write to the System Out / Err which are not inside a JavaFX thread causing unexpected exceptions and making the plugin fail

2) The redirect is redirecting output that does not belong to AEMDC and hide it from the Plugin console.

Contemplating multiple solutions I thing this might be the right one:

1) Create a JavaFX output stream wrapper that takes the original System Out and Error stream and the Console
2) That wrapper then checks if the thread is JavaFx and then either writes it to the original stream or to the Console
3) Console should be changed to writing bigger chunks that a single character as the test would add additional time

Let me know if that works for you.

**Comment by schaefa** [comment]
Dealing with System.out / err is not very performant and requires a lot of threading code.

It would be much better if you guys could use a log appender to write to the log panel.

**Comment by mtstv** [comment]
PR #9 has been merged with master.
Fixed, closed.
Thanks for contribution!
