### ISSUE TITLE
Copy Path and Packages do not match

### ISSUE THREAD

**Issue by schaefa** [headwirecom/aemdc#7]
Generating a safemethods servlet and settings package to "test.two" will create the file inside com.headwire.aemdc.sample.servlets/two but that Servlet's package is set to test.two.

Java Path and Package are both the same (dots -> slashes): com.headwire.aemdc.samples.

I would expect that the file is copied into "com/headwire/aemdc/samples/servlets/test/two" sub folder and package set to "com.headwire.aemdc.samples.servlets.test.two".

**Comment by mtstv** [comment]
Hi, it is not clear.
1) what was your command line?
2) can you provide aemdc-config.properties ?
3) was the /aemdc-files/servlet/config.properties modified?

**Comment by schaefa** [comment]
1. Wasn't CLI but UI. That said it fails for CLI as well
2. See below
3. No

This is the CLI I used:

java -jar ../../../../../../aemdc.hw/aemdc/target/aemdc-0.10.2-SNAPSHOT-jar-with-dependencies.jar servlet safemethods MyTest java-package=three.two.one java-class=MyTestServlet

This will create the servlet in the folder:

core/src/main/java/com/headwire/aemdc/samples/servlet/mytest

But the servlet has the **package**:

three.two.one

and not:

com.headwire.aemdc.samples.servlet.mytest

or **better and what I expected**:

com.headwire.aemdc.samples.servlet.three.two.one

In addition the servlet should be placed in the folder:

core/src/main/java/com/headwire/aemdc/samples/servlet/three/two/one

Cheers - Andy

# Source folders
SOURCE_FOLDER=/Users/schaefa/Development/headwire/AdobeAEM.projects/HW.AEM.Tooling.Development/aemdc.hw/aemdc-files
SOURCE_TYPES_FOLDER={{SOURCE_FOLDER}}

# Target folders
TARGET_UI_FOLDER=ui.apps/src/main/content/jcr_root
TARGET_PROJECT_APPS_FOLDER=base
TARGET_PROJECT_CONF_FOLDER=base
TARGET_PROJECT_DESIGN_FOLDER=base
TARGET_PROJECT_ROOT={{TARGET_UI_FOLDER}}/apps/{{TARGET_PROJECT_APPS_FOLDER}}
TARGET_JAVA_FOLDER=core/src/main/java
TARGET_JAVA_PACKAGE=com.headwire.aemdc.samples
TARGET_JAVA_PACKAGE_FOLDER={{TARGET_JAVA_FOLDER}}/com/headwire/aemdc/samples
TARGET_JAVA_MODEL_SUBPACKAGE={{ PH_TARGET_JAVA_MODEL_SUBPACKAGE }}
TARGET_OSGI_SUBFOLDER=/configuration

# Other config properties
FILES_WITH_PLACEHOLDERS_EXTENSIONS=xml,java,html,jsp,js,css,properties
FORBIDDEN_TEMPLATE_TYPES=.git,.settings,target,help,.idea
EXISTING_DESTINATION_RESOURCES_REPLACEMENT=MERGE
LOG_LEVEL=INFO

**Comment by mtstv** [comment]
"java-package=three.two.one" means that Java Package in the java class will be completely replaced with value "three.two.one" from command line.

The target ROOT path is ONLY defined in the aemdc-config.properties by the next 2 properties
TARGET_JAVA_PACKAGE=com.headwire.aemdc.samples
TARGET_JAVA_PACKAGE_FOLDER={{TARGET_JAVA_FOLDER}}/com/headwire/aemdc/samples

If you  want to put your Java class under "three.two.one" subpackage you must use the "target name argument" in the command line like this:
1) In case if the template type is "FILE", see /aemdc-files/servlet/config.properties
aemdc servlet safemethods three/two/one/MyTestServlet

Result file: ../com/headwire/aemdc/samples/servlet/three/two/one/MyTestServlet.java
Result java package in the MyTestServlet.java file: com.headwire.aemdc.samples.servlet.three.two.one;

2) In case if the template type is "DIR"
aemdc servlet safemethods three/two/one/mytest java-class=MyTestServlet

Result file: ../com/headwire/aemdc/samples/servlet/three/two/one/mytest/MyTestServlet.java
Result java package in the MyTestServlet.java file: com.headwire.aemdc.samples.servlet.three.two.one.mytest;

**Comment by mtstv** [comment]
I think now that we should exclude "java-package" from command line arguments like we did with "targetname" placeholder, because this placeholder will be replaced automatically.

**Comment by schaefa** [comment]
This is exactly the reason why I don’t use these types of tools.

At the end of the day I am faster copying a working and most fully configured Servlet from
another project. Even if I don’t have a class like that (for example a Sling Module) I am faster
looking it up on the Internet and copy someone else example.

The time it takes to setup a class compared to actually coding its logic is so small that
I rather take some time getting it right than having it fast.

This is a perfect example where a simple tasks of creating a servlet needs so much
time to get it right. If I struggle then what does a less experienced developer do?

I tried to use the help system on the CLI to get it going but that did not help. This is what
I thought about it:

1) aemdc help servlet safemethods is still printing <type> and [name]. It should replace them to make sure the user understands the rest
2) What is a ‘Target servlet class class sub package name’? Examples?
3) args: java-package and java-class are not document nor indicated if they are optional

Also the generated code is not adding support for OSGi (active, modified, deactivated).

**Comment by mtstv** [comment]
I understand, but it is still in dev and bugfixing phase. All improvements and suggestions are welcome.

**Comment by mtstv** [comment]
I hope I can close it. If there are still some questions please reopen again
